version: 2

updates:

  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "daily"
    ignore:
      - dependency-name: "boto3"
        update-types: [ "version-update:semver-patch" ]
    versioning-strategy: "increase"

  - package-ecosystem: "npm"
    directory: "docs/"
    schedule:
      interval: "daily"
    versioning-strategy: "increase"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"