version: 2

updates:

  - package-ecosystem: "pip"
    directory: "/src/layers/api"
    schedule:
      interval: "daily"
  - package-ecosystem: "pip"
    directory: "/src/layers/databases"
    schedule:
      interval: "daily"
  - package-ecosystem: "pip"
    directory: "/src/layers/utils"
    schedule:
      interval: "daily"
  - package-ecosystem: "pip"
    directory: "src/lambdas/api"
    schedule:
      interval: "daily"

  - package-ecosystem: "npm"
    directory: "docs/"
    schedule:
      interval: "daily"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"