env:
  browser: true
  es2021: true
  node: false
  jquery: false
parserOptions:
  ecmaVersion: 12
rules:
    semi:
      - error
      - always
    no-unused-vars:
      - error
      - args: after-used
        vars: all
        ignoreRestSiblings: false
    quotes:
      - error
      - single
