AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Resources:

  ReviewsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: username
          AttributeType: S
        - AttributeName: api_info
          AttributeType: S
      KeySchema:
        - AttributeName: username
          KeyType: HASH
        - AttributeName: api_info
          KeyType: RANGE
      BillingMode:
        PAY_PER_REQUEST
      LocalSecondaryIndexes:
        - IndexName: latest_watch_date
          KeySchema:
            - AttributeName: latest_watch_date
              KeyType: RANGE
          Projection:
            ProjectionType: ALL