AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Parameters:
  DomainName:
    Type: String

  HostedZoneId:
    Type: String
    Default: ThirdPartyZone

Resources:
  Certificate:
    Type: AWS::CertificateManager::Certificate
    Properties:
      DomainName: !Sub "auth.${DomainName}"
#      DomainValidationOptions:
#        - DomainName: !Sub "auth.${DomainName}"
#          HostedZoneId: !Ref HostedZoneId
      ValidationMethod: DNS