AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Parameters:
  DomainName:
    Type: String

  HostedZoneId:
    Type: String

Resources:
#  ItemUpdatesTopic:
#    Type: AWS::SNS::Topic
#    Properties:
#      Subscription:
#        - Subscription

  Certificate:
    Type: AWS::CertificateManager::Certificate
    Properties:
      DomainName: !Sub "api.${DomainName}"
      DomainValidationOptions:
        - DomainName: !Sub "api.${DomainName}"
          HostedZoneId: !Ref HostedZoneId
      ValidationMethod: DNS

  Gateway:
    Type: AWS::Serverless::HttpApi
    Properties:
      Auth:
        Authorizers:
          CognitoAuthorizer:
            IdentitySource: $request.header.Authorization
            JwtConfiguration:
              issuer: https://cognito-idp.eu-west-1.amazonaws.com/eu-west-1_sJ3Y4kSv6   # TODO move cognito creation to this repo and use Ref here
              audience: 68v5rahd0sdvrmf7fgbq2o1a9u
        DefaultAuthorizer: CognitoAuthorizer
      CorsConfiguration:
        AllowHeaders:
          - "authorization"
          - "content-type"
        AllowMethods:
          - "GET"
          - "POST"
          - "PUT"
          - "DELETE"
        AllowOrigins:
          - !Sub "https://${DomainName}"
      DisableExecuteApiEndpoint: true
      Domain:
        CertificateArn: !Ref Certificate
        DomainName: !Sub "api.${DomainName}"
        EndpointConfiguration: REGIONAL
        Route53:
          HostedZoneId: !Ref HostedZoneId
        SecurityPolicy: TLS_1_2