name: auto-merge

on:
 pull_request_target:

jobs:
 auto-merge:
   runs-on: ubuntu-latest
   if: ${{ github.actor == 'dependabot[bot]' && github.event_name == 'pull_request_target'}}
   steps:
     - uses: actions/checkout@v4

     - name: Merge PR
       env:
         GH_TOKEN: ${{ secrets.AUTO_MERGE_TOKEN }}
       shell: bash
       run: gh pr merge ${{ github.event.pull_request.number }} --auto