name: deploy

on:
  push:
    tags:
      - '*'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v2

      - run: |
          pip install -r src/lambdas/api/watch_histories/requirements.txt --target src/lambdas/api/watch_histories/

      - name: cdk deploy
        uses: youyo/aws-cdk-github-actions@v2.0.2
        with:
          cdk_stack: watch-history
          cdk_version: 1.128.0
          cdk_subcommand: deploy
          debug_log: true
          working_dir: deploy
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: eu-west-1
          PIP_NO_CACHE_DIR: off
          TMDB_TOKEN: ${{ secrets.TMDB_TOKEN }}
