name: deploy

on:
  push:
    tags:
      - '*'
      - one-db

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        with:
          python-version: "3.9"

      - uses: aws-actions/setup-sam@v1

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: eu-west-1
          role-to-assume: ${{ secrets.DEPLOY_ROLE_ARN }}
          role-session-name: GitHubDeploySession

      - name: build
        run: sam build --use-container

      - name: deploy
        run: |
          sam deploy --parameter-overrides
            DomainName=${{ secrets.DOMAIN_NAME }}
            HostedZoneId=${{ secrets.HOSTED_ZONE_ID }}
            TmdbToken=${{ secrets.TMDB_TOKEN }}



